# Model
#xsize: 128
#ysize: 128
xsize: 256
ysize: 256
#xsize: 512
#ysize: 512
batch_size: 32
#arch: [[64,3], [128,4], [256,6],[512,3]]
#arch: [[6,3], [12,3], [14,3], [28,4], [56,6],[128,3]]
arch: [[6,3],[6,3], [12,3], [14,3], [28,4], [56,6],[128,3]]
arch: [[6,3], [12,3], [14,3], [28,4], [56,6],[128,3]]
arch: [[6,3], [6,3], [12,3], [32,3], [128,3], [128,3]]
arch: [[16,3], [32,3], [64,3], [128,3], [128,3]]
head_arch: [3000, 3000]
head_arch: [2048, 2048, 1024]
#head_arch: [2048, 2048]
resnet50: True
shortcut2: False
arc_cos_rad: -32
arc_cos_margin: 0.001
gpu: 0
in_ch: 3
out_cls: 3 # 3
res_unit_out_relu: True
hcf_list: [std]
hcf_list: [LoG]
hcf_list: [Grad, mean]
dropout: 0
min_feat_map_size: 4
weight_decay: 0.0001 #0.0001
# optimizers
optim: 'SGD'
#optim: 'Adam'
lr: 0.01

sched: "cosine"
desc: 'New test'
checkpoints_dir: 'C:\Users\shimon.cohen\PycharmProjects\new_slidecore\model\checkpoints'
##### Data set Params   #############
#train_set_dir: 'C:\Users\shimon.cohen\data\medica\imgdb\imgdb\train_set'
train_set_dir: 'C:\Users\shimon.cohen\data\medica\imgdb\db_train_set\train_set'
train_csv_file: 'C:\Users\shimon.cohen\data\medica\imgdb\db_train_set\train_set\good_bad_train_shimon.cohen.csv'
train_csv_file: '/mnt/medica/medica_data/merged_train.csv'
test_csv_file: '/mnt/medica/medica_data/merged_train.csv'
checkpoints_dir: '/mnt/medica/checkpoints'
#test_set_dir: 'C:\Users\shimon.cohen\data\medica\imgdb\imgdb\test_set'
test_set_dir: 'C:\Users\shimon.cohen\data\medica\imgdb\db_test_set\test_set'
train_good: 'GoodFocus'
train_bad: 'BadFocus'
train_relv: 'NotRelevant'
test_good: 'GoodFocus'
test_bad: 'BadFocus'
end_str: '.jpeg'

nepochs: 220
num_workers: 4

augmentations: [RandomScale, GaussNoise, Blur, OpticalDistortion, Flip]
augmentations: [GaussNoise, Blur, OpticalDistortion, Flip]
#augmentations: [RandomScale, GaussNoise, Blur, OpticalDistortion, Flip, CLAHE,Posterize]