model_path=r"C:\Users\shimon.cohen\PycharmProjects\new_slidecore\model\output_model\resnet_epoch_17_0.924198.pt"
inference_size=0
bad_dir=r"D:\medica_data\ReScan_bad"
good_dir=r""
out_dir=r"D:\medica_output"
classifer_tile_thr=0.4           # 0.5
classifer_slide_thr=0.3
write_tiles_into_out_dir = True
bad_dir = r"E:\medica_data\ReScan_bad"
good_dir=r"E:\medica_data\ReScan_God"